CONSORTIUM="$1"

ORDERER_DOMAIN="$2"
ORDERER_MSP="$3"
ORDERER_NAME="$4"

ORG_DOMAIN="$5"
ORG_MSP="$6"
ORG_NAME="$7"


#TOOD: orderer solo to kafka


echo "---"
echo ""
echo "Profiles:"
echo ""
echo "    OneOrgOrdererGenesis:"
echo "        Capabilities:"
echo "            <<: *ChannelCapabilities"
echo "        Orderer:"
echo "            <<: *OrdererDefaults"
echo "            Organizations:"
echo "                - *OrdererOrg"
echo "            Capabilities:"
echo "                <<: *OrdererCapabilities"
echo "        Consortiums:"
echo "            ${CONSORTIUM}:"
echo "                Organizations:"
echo "                    - *Org"
echo "                    "
echo "    OneOrgChannel:"
echo "        Consortium: ${CONSORTIUM}"
echo "        Application:"
echo "            <<: *ApplicationDefaults"
echo "            Organizations:"
echo "                - *Org"
echo "            Capabilities:"
echo "                <<: *ApplicationCapabilities"
echo ""
echo "Organizations:"
echo ""
echo "    - &OrdererOrg"
echo "        Name: ${ORDERER_NAME}"
echo "        ID: ${ORDERER_MSP}"
echo "        MSPDir: crypto-config/ordererOrganizations/${ORDERER_DOMAIN}/msp"
echo ""
echo "    - &Org"
echo "        Name: ${ORG_NAME}"
echo "        ID: ${ORG_MSP}"
echo "        MSPDir: crypto-config/peerOrganizations/${ORG_DOMAIN}/msp"
echo "        AnchorPeers:"
echo "            - Host: peer0.${ORG_DOMAIN}"
echo "              Port: 7051"
echo ""
echo "Orderer: &OrdererDefaults"
echo ""
echo "    OrdererType: solo"
echo "    Addresses:"
echo "        - ${ORDERER_NAME}.${ORDERER_DOMAIN}:7050"
echo "    BatchTimeout: 2s"
echo "    BatchSize:"
echo "        MaxMessageCount: 10"
echo "        AbsoluteMaxBytes: 99 MB"
echo "        PreferredMaxBytes: 512 KB"
echo "    Kafka:"
echo "        Brokers:"
echo "            - 127.0.0.1:9092"
echo "    Organizations:"
echo ""
echo ""
echo "Application: &ApplicationDefaults"
echo "    Organizations:"
echo ""
echo ""
echo "Capabilities:"
echo "    Global: &ChannelCapabilities"
echo "        V1_1: true"
echo "    Orderer: &OrdererCapabilities"
echo "        V1_1: true"
echo "    Application: &ApplicationCapabilities"
echo "        V1_1: true"
