#!/bin/bash
orderer_domain="$1"
orderer_msp="$2"
orderer_name="$3"

ORDERER_IMAGE_TAG="x86_64-1.1.0"

echo "version: '2'"
echo ""
echo "volumes:"
echo "  ${orderer_name}.${orderer_domain}:"
echo ""
echo "networks:"
echo "  byfn:"
echo ""
echo "services:"
echo ""
echo "  ${orderer_name}.${orderer_domain}:"
echo "    image: hyperledger/fabric-orderer:${ORDERER_IMAGE_TAG}"
echo "    environment:"
echo "      - ORDERER_GENERAL_LOGLEVEL=INFO"
echo "      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0"
echo "      - ORDERER_GENERAL_GENESISMETHOD=file"
echo "      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/${orderer_name}.genesis.block"
echo "      - ORDERER_GENERAL_LOCALMSPID=${orderer_msp}"
echo "      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp"
echo "      - ORDERER_GENERAL_TLS_ENABLED=false"
echo "      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key"
echo "      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt"
echo "      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]"
echo "    working_dir: /opt/gopath/src/github.com/hyperledger/fabric"
echo "    command: orderer"
echo "    volumes:"
echo "    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/${orderer_name}.genesis.block"
echo "    - ./crypto-config/ordererOrganizations/${orderer_domain}/orderers/${orderer_name}.${orderer_domain}/msp:/var/hyperledger/orderer/msp"
echo "    - ./crypto-config/ordererOrganizations/${orderer_domain}/orderers/${orderer_name}.${orderer_domain}/tls/:/var/hyperledger/orderer/tls"
echo "    - ${orderer_name}.${orderer_domain}:/var/hyperledger/production/orderer"
echo "    ports:"
echo "      - 7050:7050"
echo "    container_name: ${orderer_name}.${orderer_domain}"
echo "    networks:"
echo "      - byfn"
echo "    extra_hosts:"
echo "      - \"orderer.dota.com:172.24.10.78\""
echo "      - \"peer0.dota.com:172.24.10.78\""
echo "      - \"orderer.upltv.com:172.24.20.171\""
echo "      - \"peer0.org1.upltv.com:172.24.20.171\""
echo "      - \"peer0.google.com:172.24.11.16\""

exit 0
